# ! be mindful that you need to set the project region and id according to your GCP project here
steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'europe-west6-docker.pkg.dev/PROJECT_ID/REGISTRY_REPO_NAME/IMAGE_NAME:$TAG_NAME', '.']
    id: Build
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - 'europe-west6-docker.pkg.dev/PROJECT_ID/REGISTRY_REPO_NAME/IMAGE_NAME:$TAG_NAME'
    id: Push
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    args:
      - run
      - services
      - update
      - mytestservice
      - '--platform=managed'
      - '--image=europe-west6-docker.pkg.dev/PROJECT_ID/REGISTRY_REPO_NAME/IMAGE_NAME:$TAG_NAME'
      - >-
        --labels=managed-by=gcp-cloud-build-deploy-cloud-run,commit-sha=$COMMIT_SHA,gcb-build-id=$BUILD_ID
      - '--region=europe-west6'
      - '--quiet'
    id: Deploy
    entrypoint: gcloud
images:
  - 'europe-west6-docker.pkg.dev/PROJECT_ID/REGISTRY_REPO_NAME/IMAGE_NAME:$TAG_NAME'
options:
  substitutionOption: ALLOW_LOOSE
tags:
  - gcp-cloud-build-deploy-cloud-run
  - gcp-cloud-build-deploy-cloud-run-managed
  - php